"""
Conversion Models
SQLAlchemy models for measure conversion tracking and management
"""

from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from src.db.base import Base


class ConversionHistory(Base):
    """
    Track conversion job history for audit trail and analytics.

    Stores all conversion attempts with input/output data, timing,
    and status for debugging, analytics, and compliance.
    """

    __tablename__ = "conversion_history"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Execution tracking
    execution_id = Column(
        String(100), nullable=True, index=True
    )  # Optional link to crew execution
    job_id = Column(
        String(100), nullable=True, index=True
    )  # Link to ConversionJob if async

    # Conversion details
    source_format = Column(
        String(50), nullable=False, index=True
    )  # powerbi, yaml, etc.
    target_format = Column(
        String(50), nullable=False, index=True
    )  # dax, sql, uc_metrics, yaml

    # Data (stored as JSON for flexibility)
    input_data = Column(JSON, nullable=True)  # Source data
    input_summary = Column(Text, nullable=True)  # Human-readable summary
    output_data = Column(JSON, nullable=True)  # Generated output
    output_summary = Column(Text, nullable=True)  # Human-readable summary

    # Configuration used
    configuration = Column(JSON, nullable=True)  # Converter configuration parameters

    # Status and results
    status = Column(
        String(20), nullable=False, default="pending"
    )  # pending, running, success, failed
    error_message = Column(Text, nullable=True)
    warnings = Column(JSON, nullable=True)  # List of warning messages

    # Metrics
    measure_count = Column(Integer, nullable=True)  # Number of measures converted
    execution_time_ms = Column(Integer, nullable=True)  # Execution time in milliseconds

    # Metadata
    converter_version = Column(String(50), nullable=True)  # Version of converter used
    extra_metadata = Column(JSON, nullable=True)  # Additional metadata

    # Multi-tenant isolation
    group_id = Column(String(100), index=True, nullable=True)
    created_by_email = Column(String(255), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Indexes for common queries
    __table_args__ = (
        Index("ix_conversion_history_group_created", "group_id", "created_at"),
        Index("ix_conversion_history_status_created", "status", "created_at"),
        Index("ix_conversion_history_formats", "source_format", "target_format"),
    )

    def __repr__(self):
        return (
            f"<ConversionHistory(id={self.id}, "
            f"{self.source_format}->{self.target_format}, "
            f"status={self.status})>"
        )


class ConversionJob(Base):
    """
    Track async conversion jobs for long-running conversions.

    Enables background processing of large conversions with
    progress tracking, status updates, and result retrieval.
    """

    __tablename__ = "conversion_jobs"

    # Primary key (UUID for distributed systems)
    id = Column(String(100), primary_key=True)  # UUID generated by application

    # Job details
    name = Column(String(255), nullable=True)  # User-friendly name
    description = Column(Text, nullable=True)

    # Tool association
    tool_id = Column(Integer, ForeignKey("tools.id"), nullable=True)

    # Conversion configuration
    source_format = Column(String(50), nullable=False)
    target_format = Column(String(50), nullable=False)
    configuration = Column(JSON, nullable=False)  # Full converter configuration

    # Job status
    status = Column(
        String(20), nullable=False, default="pending"
    )  # pending, running, completed, failed, cancelled
    progress = Column(Float, nullable=True)  # 0.0 to 1.0 (0% to 100%)

    # Results
    result = Column(JSON, nullable=True)  # Conversion result
    error_message = Column(Text, nullable=True)

    # Execution tracking
    execution_id = Column(
        String(100), nullable=True, index=True
    )  # Link to crew execution
    history_id = Column(
        Integer, ForeignKey("conversion_history.id"), nullable=True
    )  # Link to history

    # Metadata
    extra_metadata = Column(JSON, nullable=True)

    # Multi-tenant isolation
    group_id = Column(String(100), index=True, nullable=True)
    created_by_email = Column(String(255), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    tool = relationship("Tool", foreign_keys=[tool_id])
    history = relationship("ConversionHistory", foreign_keys=[history_id])

    # Indexes
    __table_args__ = (
        Index("ix_conversion_jobs_group_created", "group_id", "created_at"),
        Index("ix_conversion_jobs_status", "status"),
    )

    def __repr__(self):
        return (
            f"<ConversionJob(id={self.id}, "
            f"name={self.name}, "
            f"status={self.status}, "
            f"progress={self.progress})>"
        )


class SavedConverterConfiguration(Base):
    """
    User-saved converter configurations for reuse.

    Allows users to save frequently used converter configurations
    with custom names for quick access.
    """

    __tablename__ = "saved_converter_configurations"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Configuration details
    name = Column(String(255), nullable=False)  # User-friendly name
    description = Column(Text, nullable=True)

    # Converter type
    source_format = Column(String(50), nullable=False)
    target_format = Column(String(50), nullable=False)

    # Configuration (JSON storage)
    configuration = Column(JSON, nullable=False)  # Full converter configuration

    # Usage tracking
    use_count = Column(Integer, default=0, nullable=False)  # Number of times used
    last_used_at = Column(DateTime, nullable=True)

    # Sharing
    is_public = Column(Boolean, default=False, nullable=False)  # Shared with group
    is_template = Column(Boolean, default=False, nullable=False)  # System template

    # Metadata
    tags = Column(JSON, nullable=True)  # List of tags for categorization
    extra_metadata = Column(JSON, nullable=True)

    # Multi-tenant isolation
    group_id = Column(String(100), index=True, nullable=True)
    created_by_email = Column(String(255), nullable=False, index=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Indexes
    __table_args__ = (
        Index("ix_saved_configs_group_user", "group_id", "created_by_email"),
        Index("ix_saved_configs_formats", "source_format", "target_format"),
        Index("ix_saved_configs_public", "is_public", "is_template"),
    )

    def __repr__(self):
        return (
            f"<SavedConverterConfiguration(id={self.id}, "
            f"name={self.name}, "
            f"{self.source_format}->{self.target_format})>"
        )
