"""
Conversion Models
SQLAlchemy models for measure conversion tracking and management
"""

from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.db.base import Base


class ConversionHistory(Base):
    """
    Track conversion job history for audit trail and analytics.

    Stores all conversion attempts with input/output data, timing,
    and status for debugging, analytics, and compliance.
    """

    __tablename__ = "conversion_history"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Execution tracking
    execution_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, index=True
    )  # Optional link to crew execution
    job_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, index=True
    )  # Link to ConversionJob if async

    # Conversion details
    source_format: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )  # powerbi, yaml, etc.
    target_format: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )  # dax, sql, uc_metrics, yaml

    # Data (stored as JSON for flexibility)
    input_data: Mapped[Any] = mapped_column(JSON, nullable=True)  # Source data
    input_summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )  # Human-readable summary
    output_data: Mapped[Any] = mapped_column(JSON, nullable=True)  # Generated output
    output_summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )  # Human-readable summary

    # Configuration used
    configuration: Mapped[Any] = mapped_column(
        JSON, nullable=True
    )  # Converter configuration parameters

    # Status and results
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )  # pending, running, success, failed
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    warnings: Mapped[Any] = mapped_column(
        JSON, nullable=True
    )  # List of warning messages

    # Metrics
    measure_count: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )  # Number of measures converted
    execution_time_ms: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )  # Execution time in milliseconds

    # Metadata
    converter_version: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True
    )  # Version of converter used
    extra_metadata: Mapped[Any] = mapped_column(
        JSON, nullable=True
    )  # Additional metadata

    # Multi-tenant isolation
    group_id: Mapped[Optional[str]] = mapped_column(
        String(100), index=True, nullable=True
    )
    created_by_email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Indexes for common queries
    __table_args__ = (
        Index("ix_conversion_history_group_created", "group_id", "created_at"),
        Index("ix_conversion_history_status_created", "status", "created_at"),
        Index("ix_conversion_history_formats", "source_format", "target_format"),
    )

    def __repr__(self) -> str:
        return (
            f"<ConversionHistory(id={self.id}, "
            f"{self.source_format}->{self.target_format}, "
            f"status={self.status})>"
        )


class ConversionJob(Base):
    """
    Track async conversion jobs for long-running conversions.

    Enables background processing of large conversions with
    progress tracking, status updates, and result retrieval.
    """

    __tablename__ = "conversion_jobs"

    # Primary key (UUID for distributed systems)
    id: Mapped[str] = mapped_column(
        String(100), primary_key=True
    )  # UUID generated by application

    # Job details
    name: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True
    )  # User-friendly name
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Tool association
    tool_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("tools.id"), nullable=True
    )

    # Conversion configuration
    source_format: Mapped[str] = mapped_column(String(50), nullable=False)
    target_format: Mapped[str] = mapped_column(String(50), nullable=False)
    configuration: Mapped[Any] = mapped_column(
        JSON, nullable=False
    )  # Full converter configuration

    # Job status
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )  # pending, running, completed, failed, cancelled
    progress: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True
    )  # 0.0 to 1.0 (0% to 100%)

    # Results
    result: Mapped[Any] = mapped_column(JSON, nullable=True)  # Conversion result
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Execution tracking
    execution_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, index=True
    )  # Link to crew execution
    history_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("conversion_history.id"), nullable=True
    )  # Link to history

    # Metadata
    extra_metadata: Mapped[Any] = mapped_column(JSON, nullable=True)

    # Multi-tenant isolation
    group_id: Mapped[Optional[str]] = mapped_column(
        String(100), index=True, nullable=True
    )
    created_by_email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Relationships
    tool = relationship("Tool", foreign_keys=[tool_id])
    history = relationship("ConversionHistory", foreign_keys=[history_id])

    # Indexes
    __table_args__ = (
        Index("ix_conversion_jobs_group_created", "group_id", "created_at"),
        Index("ix_conversion_jobs_status", "status"),
    )

    def __repr__(self) -> str:
        return (
            f"<ConversionJob(id={self.id}, "
            f"name={self.name}, "
            f"status={self.status}, "
            f"progress={self.progress})>"
        )


class SavedConverterConfiguration(Base):
    """
    User-saved converter configurations for reuse.

    Allows users to save frequently used converter configurations
    with custom names for quick access.
    """

    __tablename__ = "saved_converter_configurations"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Configuration details
    name: Mapped[str] = mapped_column(String(255), nullable=False)  # User-friendly name
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Converter type
    source_format: Mapped[str] = mapped_column(String(50), nullable=False)
    target_format: Mapped[str] = mapped_column(String(50), nullable=False)

    # Configuration (JSON storage)
    configuration: Mapped[Any] = mapped_column(
        JSON, nullable=False
    )  # Full converter configuration

    # Usage tracking
    use_count: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False
    )  # Number of times used
    last_used_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Sharing
    is_public: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )  # Shared with group
    is_template: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )  # System template

    # Metadata
    tags: Mapped[Any] = mapped_column(
        JSON, nullable=True
    )  # List of tags for categorization
    extra_metadata: Mapped[Any] = mapped_column(JSON, nullable=True)

    # Multi-tenant isolation
    group_id: Mapped[Optional[str]] = mapped_column(
        String(100), index=True, nullable=True
    )
    created_by_email: Mapped[str] = mapped_column(
        String(255), nullable=False, index=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Indexes
    __table_args__ = (
        Index("ix_saved_configs_group_user", "group_id", "created_by_email"),
        Index("ix_saved_configs_formats", "source_format", "target_format"),
        Index("ix_saved_configs_public", "is_public", "is_template"),
    )

    def __repr__(self) -> str:
        return (
            f"<SavedConverterConfiguration(id={self.id}, "
            f"name={self.name}, "
            f"{self.source_format}->{self.target_format})>"
        )
