"""DallETool — image generation."""

import json
import logging
import os
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from .base import BaseTool, EnvVar

logger = logging.getLogger(__name__)

class ImagePromptSchema(BaseModel):
    """Input for Dall-E Tool."""

    image_description: str = Field(
        description="Description of the image to be generated by Dall-E."
    )


class DallETool(BaseTool):
    name: str = "Dall-E Tool"
    description: str = "Generates images using OpenAI's Dall-E model."
    args_schema: type[BaseModel] = ImagePromptSchema

    model: str = "dall-e-3"
    size: (
        Literal[
            "auto",
            "1024x1024",
            "1536x1024",
            "1024x1536",
            "256x256",
            "512x512",
            "1792x1024",
            "1024x1792",
        ]
        | None
    ) = "1024x1024"
    quality: Literal["standard", "hd", "low", "medium", "high", "auto"] | None = (
        "standard"
    )
    n: int = 1

    env_vars: list[EnvVar] = Field(
        default_factory=lambda: [
            EnvVar(
                name="OPENAI_API_KEY",
                description="API key for OpenAI services",
                required=True,
            ),
        ]
    )

    def _run(self, **kwargs: Any) -> str:
        image_description = kwargs.get("image_description")
        if not image_description:
            return "Image description is required."

        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            return "OPENAI_API_KEY is not set."

        base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
        try:
            response = _http_json(
                f"{base_url}/images/generations",
                {
                    "model": self.model,
                    "prompt": image_description,
                    "size": self.size,
                    "quality": self.quality,
                    "n": self.n,
                },
                {"Authorization": f"Bearer {api_key}"},
                timeout=60,
            )
        except (RuntimeError, ValueError) as e:
            return f"Failed to generate image: {e}"

        data = response.get("data") or []
        if not data:
            return "Failed to generate image."
        return json.dumps(
            {
                "image_url": data[0].get("url"),
                "image_description": data[0].get("revised_prompt"),
            }
        )
