/**
 * TypeScript interfaces for the Pipeline Config Editor.
 * Covers all 26 keys generated by Tool 90 (Pipeline Config Generator).
 */

// ── Nested value types ──────────────────────────────────────────

export interface JoinKeyEntry {
  alias: string;
  join_key: string;
  dim_columns: string[];
  dim_key?: string;
}

export interface FactJoinEntry {
  join_expr: string;
  dim_aliases: string[];
  [key: string]: unknown;
}

export interface EnrichmentJoinEntry {
  name: string;
  source: string;
  join_on: string;
  dim_columns: string[];
}

export interface SwitchDecompositionEntry {
  name: string;
  raw_expr: string;
  comment: string;
}

export interface MeasureResolutionEntry {
  base_expr: string;
  base_filters: string[];
}

export interface ManualOverrideEntry {
  sql_expr: string;
  comment: string;
  [key: string]: unknown;
}

export interface MappingOnlyTableEntry {
  source_table: string;
  dimensions: string[];
}

export interface ColumnMetadataEntry {
  data_type: string;
  is_hidden: boolean;
  format_string?: string;
  [key: string]: unknown;
}

// ── Full pipeline config (26 keys) ─────────────────────────────

export interface PipelineConfig {
  // JOIN CONFIGURATION (keys 1-4)
  join_key_map: Record<string, JoinKeyEntry>;
  fact_join_map: Record<string, FactJoinEntry>;
  enrichment_joins: Record<string, EnrichmentJoinEntry[]>;
  dim_alias_map: Record<string, string>;

  // MEASURE & SWITCH LOGIC (keys 5-11)
  switch_decompositions: Record<string, SwitchDecompositionEntry[]>;
  measure_resolutions: Record<string, MeasureResolutionEntry>;
  // How many other measures reference each measure (in-degree). Surfaced next to
  // TODO entries so reviewers prioritize high-impact gaps. Measure refs only.
  measure_usage?: Record<string, number>;
  filter_sets: Record<string, string[]>;
  manual_overrides: Record<string, ManualOverrideEntry>;
  budget_suffix: string | null;
  switch_join_alias: string | null;
  switch_join_col: string | null;

  // COLUMN & METADATA (keys 12-17)
  column_metadata: Record<string, ColumnMetadataEntry>;
  column_overrides: Record<string, unknown>;
  column_alias_map: Record<string, string>;
  comment_overrides: Record<string, string>;
  measure_metadata: Record<string, string>;
  dimension_metadata: Record<string, unknown>;

  // TIME/PERIOD DIMENSIONS (keys 18-19)
  period_dim_priority: string[];
  int_period_dims: string[];

  // FILTERING & PARAMETERS (keys 20-22)
  parameter_defaults: Record<string, string>;
  cwc_filter_column: string | null;
  percentage_multiplier_patterns: string[];

  // NAME NORMALIZATION (keys 23-25)
  name_prefixes_to_strip: string[];
  dimension_order: Record<string, string[]>;
  dimension_exclusions: Record<string, string[]>;

  // SPECIAL CASES (key 26)
  mapping_only_tables: Record<string, MappingOnlyTableEntry>;

  // Allow additional keys
  [key: string]: unknown;
}

// ── Key status tracking ─────────────────────────────────────────

export type ConfigKeyStatus = 'auto' | 'todo' | 'empty' | 'null';

export interface ConfigKeyInfo {
  key: string;
  status: ConfigKeyStatus;
  label: string;
  category: string;
  valueType: 'string' | 'string-nullable' | 'list' | 'dict' | 'dict-of-list' | 'dict-of-dict';
  entryCount: number;
  todoCount: number;
}

// ── Category groupings ──────────────────────────────────────────

export const CONFIG_KEY_CATEGORIES: Record<string, string[]> = {
  'Join Configuration': [
    'join_key_map', 'fact_join_map', 'enrichment_joins', 'dim_alias_map',
  ],
  'Measure & Switch Logic': [
    'switch_decompositions', 'measure_resolutions', 'filter_sets',
    'manual_overrides', 'budget_suffix', 'switch_join_alias', 'switch_join_col',
  ],
  'Column & Metadata': [
    'column_metadata', 'column_overrides', 'column_alias_map',
    'comment_overrides', 'measure_metadata', 'dimension_metadata',
  ],
  'Time / Period Dimensions': [
    'period_dim_priority', 'int_period_dims',
  ],
  'Filtering & Parameters': [
    'parameter_defaults', 'cwc_filter_column', 'percentage_multiplier_patterns',
  ],
  'Name Normalization': [
    'name_prefixes_to_strip', 'dimension_order', 'dimension_exclusions',
  ],
  'Special Cases': [
    'mapping_only_tables',
  ],
};

// Key display labels (human-readable)
export const CONFIG_KEY_LABELS: Record<string, string> = {
  join_key_map: 'Join Key Map',
  fact_join_map: 'Fact Join Map',
  enrichment_joins: 'Enrichment Joins',
  dim_alias_map: 'Dimension Alias Map',
  switch_decompositions: 'Switch Decompositions',
  measure_resolutions: 'Measure Resolutions',
  filter_sets: 'Filter Sets',
  manual_overrides: 'Manual Overrides',
  budget_suffix: 'Budget Suffix',
  switch_join_alias: 'Switch Join Alias',
  switch_join_col: 'Switch Join Column',
  column_metadata: 'Column Metadata',
  column_overrides: 'Column Overrides',
  column_alias_map: 'Column Alias Map',
  comment_overrides: 'Comment Overrides',
  measure_metadata: 'Measure Metadata',
  dimension_metadata: 'Dimension Metadata',
  period_dim_priority: 'Period Dimension Priority',
  int_period_dims: 'Integer Period Dimensions',
  parameter_defaults: 'Parameter Defaults',
  cwc_filter_column: 'CWC Filter Column',
  percentage_multiplier_patterns: '% Multiplier Patterns',
  name_prefixes_to_strip: 'Name Prefixes to Strip',
  dimension_order: 'Dimension Order',
  dimension_exclusions: 'Dimension Exclusions',
  mapping_only_tables: 'Mapping-Only Tables',
};

// ── Helper: classify a key's value type ─────────────────────────

export function classifyValueType(
  key: string,
  value: unknown,
): ConfigKeyInfo['valueType'] {
  // Nullable strings
  const nullableStringKeys = new Set([
    'budget_suffix', 'switch_join_alias', 'switch_join_col', 'cwc_filter_column',
  ]);
  if (nullableStringKeys.has(key)) return 'string-nullable';

  // Lists
  const listKeys = new Set([
    'period_dim_priority', 'int_period_dims', 'percentage_multiplier_patterns',
    'name_prefixes_to_strip',
  ]);
  if (listKeys.has(key)) return 'list';

  // Dict-of-list (values are arrays)
  const dictOfListKeys = new Set([
    'enrichment_joins', 'switch_decompositions', 'filter_sets',
    'dimension_order', 'dimension_exclusions',
  ]);
  if (dictOfListKeys.has(key)) return 'dict-of-list';

  // Dict-of-dict
  if (value && typeof value === 'object' && !Array.isArray(value)) return 'dict-of-dict';

  // Fallback
  if (Array.isArray(value)) return 'list';
  return 'string';
}

// ── Helper: determine status of a key ───────────────────────────

export function getKeyStatus(value: unknown): ConfigKeyStatus {
  if (value === null || value === undefined) return 'null';

  const str = JSON.stringify(value);

  if (str.includes('TODO')) return 'todo';

  // Check emptiness
  if (typeof value === 'string' && value.trim() === '') return 'empty';
  if (Array.isArray(value) && value.length === 0) return 'empty';
  if (typeof value === 'object' && !Array.isArray(value) && Object.keys(value as object).length === 0) return 'empty';

  return 'auto';
}

// Count TODO markers in a value
export function countTodos(value: unknown): number {
  if (value === null || value === undefined) return 0;
  const str = JSON.stringify(value);
  return (str.match(/TODO/g) || []).length;
}
