"""add tenant fields to llmlog

Revision ID: 1f0183de606
Revises: bb791d3a4812
Create Date: 2025-06-07 12:02:03.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0183de606'
down_revision = '0b2e4e50781a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llmlog', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.add_column('llmlog', sa.Column('tenant_email', sa.String(length=255), nullable=True))
    op.create_index('ix_llmlog_tenant_id', 'llmlog', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llmlog_tenant_id', table_name='llmlog')
    op.drop_column('llmlog', 'tenant_email')
    op.drop_column('llmlog', 'tenant_id')
    # ### end Alembic commands ###