"""add_temperature_field_to_agents

Revision ID: 52262b55c54d
Revises: fix_modelconfig_unique
Create Date: 2025-09-11 21:20:15.128132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52262b55c54d'
down_revision: Union[str, None] = 'fix_modelconfig_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('temperature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'temperature')
    # ### end Alembic commands ### 