"""Add user level permission fields

Revision ID: 6efefa1a1df7
Revises: 3e393f55f1eb
Create Date: 2025-09-21 12:34:16.638878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6efefa1a1df7'
down_revision: Union[str, None] = '3e393f55f1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_backends_group_id'), table_name='memory_backends')
    op.drop_table('memory_backends')
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_personal_workspace_manager', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_personal_workspace_manager')
    op.drop_column('users', 'is_system_admin')
    op.create_table('memory_backends',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('backend_type', postgresql.ENUM('DEFAULT', 'DATABRICKS', name='memorybackendtypeenum'), autoincrement=False, nullable=False),
    sa.Column('databricks_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('enable_short_term', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_long_term', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_entity', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_relationship_retrieval', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_backends_pkey'))
    )
    op.create_index(op.f('ix_memory_backends_group_id'), 'memory_backends', ['group_id'], unique=False)
    # ### end Alembic commands ### 