"""Add group_id and created_by_email to model_configs

Revision ID: 9fbe565a5288
Revises: add_multitenant_apikeys
Create Date: 2025-09-11 20:28:28.234692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fbe565a5288'
down_revision: Union[str, None] = 'add_multitenant_apikeys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_created_by_email'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_group_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('idx_task_mapping_description'), table_name='task_mappings')
    op.drop_index(op.f('idx_task_mapping_group'), table_name='task_mappings')
    op.drop_index(op.f('idx_task_mapping_lookup'), table_name='task_mappings')
    op.drop_index(op.f('ix_task_mappings_crewai_task_id'), table_name='task_mappings')
    op.drop_index(op.f('ix_task_mappings_database_task_id'), table_name='task_mappings')
    op.drop_index(op.f('ix_task_mappings_execution_id'), table_name='task_mappings')
    op.drop_index(op.f('ix_task_mappings_group_id'), table_name='task_mappings')
    op.drop_index(op.f('ix_task_mappings_task_name'), table_name='task_mappings')
    op.drop_table('task_mappings')
    op.drop_index(op.f('ix_memory_backends_group_id'), table_name='memory_backends')
    op.drop_table('memory_backends')
    op.drop_index(op.f('ix_mlflow_settings_group_id'), table_name='mlflow_settings')
    op.drop_index(op.f('ix_mlflow_settings_id'), table_name='mlflow_settings')
    op.drop_table('mlflow_settings')
    op.drop_index(op.f('ix_databricks_config_created_by_email'), table_name='databricks_config')
    op.drop_index(op.f('ix_databricks_config_group_id'), table_name='databricks_config')
    op.drop_table('databricks_config')
    op.alter_column('agents', 'tool_configs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='User-specific tool configurations override',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('idx_agents_content_hash'), table_name='agents')
    op.drop_index(op.f('idx_agents_content_hash_group'), table_name='agents')
    op.drop_column('agents', 'content_hash')
    op.drop_constraint(op.f('uq_apikey_name_group'), 'apikey', type_='unique')
    op.drop_index(op.f('idx_executionhistory_is_stopping'), table_name='executionhistory', postgresql_where='(is_stopping = true)')
    op.alter_column('mcp_servers', 'global_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('mcp_servers', 'args')
    op.drop_column('mcp_servers', 'command')
    op.alter_column('mcp_settings', 'individual_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tasks', 'tool_configs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='User-specific tool configurations override',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('idx_tasks_content_hash'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_content_hash_group'), table_name='tasks')
    op.drop_column('tasks', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_tasks_content_hash_group'), 'tasks', ['content_hash', 'group_id'], unique=False)
    op.create_index(op.f('idx_tasks_content_hash'), 'tasks', ['content_hash'], unique=False)
    op.alter_column('tasks', 'tool_configs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='User-specific tool configurations override',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('mcp_settings', 'individual_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('mcp_servers', sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('mcp_servers', 'global_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_executionhistory_is_stopping'), 'executionhistory', ['is_stopping'], unique=False, postgresql_where='(is_stopping = true)')
    op.create_unique_constraint(op.f('uq_apikey_name_group'), 'apikey', ['name', 'group_id'], postgresql_nulls_not_distinct=False)
    op.add_column('agents', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_agents_content_hash_group'), 'agents', ['content_hash', 'group_id'], unique=False)
    op.create_index(op.f('idx_agents_content_hash'), 'agents', ['content_hash'], unique=False)
    op.alter_column('agents', 'tool_configs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='User-specific tool configurations override',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.create_table('databricks_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('catalog', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('apps_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('encrypted_personal_access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('databricks_config_pkey'))
    )
    op.create_index(op.f('ix_databricks_config_group_id'), 'databricks_config', ['group_id'], unique=False)
    op.create_index(op.f('ix_databricks_config_created_by_email'), 'databricks_config', ['created_by_email'], unique=False)
    op.create_table('mlflow_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experiment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracking_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mlflow_settings_pkey')),
    sa.UniqueConstraint('group_id', name=op.f('uq_mlflow_settings_group_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mlflow_settings_id'), 'mlflow_settings', ['id'], unique=False)
    op.create_index(op.f('ix_mlflow_settings_group_id'), 'mlflow_settings', ['group_id'], unique=False)
    op.create_table('memory_backends',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('backend_type', postgresql.ENUM('DEFAULT', 'DATABRICKS', name='memorybackendtypeenum'), autoincrement=False, nullable=False),
    sa.Column('databricks_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('enable_short_term', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_long_term', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_entity', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_relationship_retrieval', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_backends_pkey'))
    )
    op.create_index(op.f('ix_memory_backends_group_id'), 'memory_backends', ['group_id'], unique=False)
    op.create_table('task_mappings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('database_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crewai_task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['database_task_id'], ['tasks.id'], name=op.f('task_mappings_database_task_id_fkey')),
    sa.ForeignKeyConstraint(['execution_id'], ['executionhistory.job_id'], name=op.f('task_mappings_execution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_mappings_pkey')),
    sa.UniqueConstraint('execution_id', 'crewai_task_id', name=op.f('uq_execution_crewai_task'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_task_mappings_task_name'), 'task_mappings', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_mappings_group_id'), 'task_mappings', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_mappings_execution_id'), 'task_mappings', ['execution_id'], unique=False)
    op.create_index(op.f('ix_task_mappings_database_task_id'), 'task_mappings', ['database_task_id'], unique=False)
    op.create_index(op.f('ix_task_mappings_crewai_task_id'), 'task_mappings', ['crewai_task_id'], unique=True)
    op.create_index(op.f('idx_task_mapping_lookup'), 'task_mappings', ['crewai_task_id', 'execution_id'], unique=False)
    op.create_index(op.f('idx_task_mapping_group'), 'task_mappings', ['group_id', 'execution_id'], unique=False)
    op.create_index(op.f('idx_task_mapping_description'), 'task_mappings', ['task_description', 'execution_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('name', 'group_id', name=op.f('uq_api_keys_name_group'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=False)
    op.create_index(op.f('ix_api_keys_group_id'), 'api_keys', ['group_id'], unique=False)
    op.create_index(op.f('ix_api_keys_created_by_email'), 'api_keys', ['created_by_email'], unique=False)
    # ### end Alembic commands ### 