"""create_user_rbac_tables

Revision ID: cd2fe0ce549e
Revises: f73d7b7af767
Create Date: 2025-06-07 14:49:03.708042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2fe0ce549e'
down_revision: Union[str, None] = 'f73d7b7af767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_external_identity_provider_user', 'external_identities', ['provider', 'provider_user_id'])
    op.create_unique_constraint('uq_role_privilege', 'role_privileges', ['role_id', 'privilege_id'])
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_privilege', 'role_privileges', type_='unique')
    op.drop_constraint('uq_external_identity_provider_user', 'external_identities', type_='unique')
    # ### end Alembic commands ### 