import { describe, expect, it } from 'vitest'
import { applyA2uiMessage, applyA2uiMessages, isSurfaceStreaming } from './stream'
import type { A2uiMessage } from './stream'
import type { Surface } from './types'
import fixture from './stream.test.fixture.json'

const MESSAGES = fixture.messages as A2uiMessage[]
const EXPECTED = fixture.expected as unknown as Surface

describe('applying a real backend stream', () => {
  // The fixture is generated BY services/a2ui/stream.py and kept in step by
  // test_stream_fixture_parity.py. This is the one test that proves the two
  // languages agree on the wire format.
  it('rebuilds exactly the surface the composer produced', () => {
    expect(applyA2uiMessages(null, MESSAGES)).toEqual(EXPECTED)
  })

  it('renders something long before the stream ends', () => {
    // The point of the exercise: a usable surface exists from the first few
    // messages, not only after the last one.
    const early = applyA2uiMessages(null, MESSAGES.slice(0, 2))
    expect(early?.root).toBe('deck')
    expect(early!.components.length).toBeGreaterThan(0)
    expect(early!.components.length).toBeLessThan(EXPECTED.components.length)
  })

  it('is monotonic — every prefix is a valid surface', () => {
    for (let i = 1; i <= MESSAGES.length; i++) {
      const s = applyA2uiMessages(null, MESSAGES.slice(0, i))
      expect(s).not.toBeNull()
      expect(s!.surfaceKind).toBe('presentation')
      expect(new Set(s!.components.map((c) => c.id)).size).toBe(s!.components.length)
    }
  })
})

describe('applyA2uiMessage', () => {
  const base: Surface = {
    surfaceKind: 'presentation',
    root: 'deck',
    components: [{ id: 'deck', component: 'SlideDeck', children: ['s1'] }],
    dataModel: {},
  }

  it('replaces a component by id rather than appending it', () => {
    // This is what lets real slides overwrite the outline skeleton in place.
    const withPlaceholder = applyA2uiMessage(base, {
      updateComponents: { surfaceId: 'x', components: [{ id: 's1', component: 'Slide', pending: true }] },
    })!
    const filled = applyA2uiMessage(withPlaceholder, {
      updateComponents: { surfaceId: 'x', components: [{ id: 's1', component: 'Slide', title: 'Real' }] },
    })!
    expect(filled.components).toHaveLength(2)
    expect(filled.components[1]).toEqual({ id: 's1', component: 'Slide', title: 'Real' })
  })

  it('does not mutate the surface it was given', () => {
    const before = JSON.stringify(base)
    applyA2uiMessage(base, {
      updateComponents: { surfaceId: 'x', components: [{ id: 's1', component: 'Slide' }] },
    })
    expect(JSON.stringify(base)).toBe(before)
  })

  it('writes a data model key from its JSON Pointer', () => {
    const out = applyA2uiMessage(base, {
      updateDataModel: { surfaceId: 'x', path: '/rows', value: [1, 2] },
    })!
    expect(out.dataModel).toEqual({ rows: [1, 2] })
  })

  it('unescapes a pointer segment', () => {
    const out = applyA2uiMessage(base, {
      updateDataModel: { surfaceId: 'x', path: '/a~1b', value: 1 },
    })!
    expect(out.dataModel).toEqual({ 'a/b': 1 })
  })

  it('deletes a key when the value is null', () => {
    const seeded = applyA2uiMessage(base, {
      updateDataModel: { surfaceId: 'x', path: '/k', value: 'v' },
    })!
    const out = applyA2uiMessage(seeded, { updateDataModel: { surfaceId: 'x', path: '/k', value: null } })!
    expect(out.dataModel).toEqual({})
  })

  it('replaces the whole data model at the root pointer', () => {
    const out = applyA2uiMessage(base, { updateDataModel: { surfaceId: 'x', path: '/', value: { a: 1 } } })!
    expect(out.dataModel).toEqual({ a: 1 })
  })

  it('retracts the surface on deleteSurface', () => {
    expect(applyA2uiMessage(base, { deleteSurface: { surfaceId: 'x' } })).toBeNull()
  })

  it('ignores an update that arrives before any surface exists', () => {
    // The protocol requires createSurface first; inventing a rootless surface
    // here would render an empty shell.
    expect(
      applyA2uiMessage(null, { updateComponents: { surfaceId: 'x', components: [{ id: 'a', component: 'Text' }] } }),
    ).toBeNull()
  })

  it.each([
    ['garbage', null as unknown as A2uiMessage],
    ['an empty message', {} as A2uiMessage],
    ['a createSurface with no root', { createSurface: { surfaceId: 'x', surfaceKind: 'document' } } as A2uiMessage],
    ['an empty component batch', { updateComponents: { surfaceId: 'x', components: [] } } as A2uiMessage],
    ['a malformed pointer', { updateDataModel: { surfaceId: 'x', path: 42 } } as unknown as A2uiMessage],
  ])('never blanks a live surface for %s', (_label, msg) => {
    // A bad delta must not take away what the reader is already looking at.
    expect(applyA2uiMessage(base, msg)).toEqual(base)
  })
})

describe('isSurfaceStreaming', () => {
  it('is true while a referenced child has not arrived', () => {
    const s = applyA2uiMessages(null, MESSAGES.slice(0, 2))
    expect(isSurfaceStreaming(s)).toBe(true)
  })

  it('is false once the whole surface has landed', () => {
    expect(isSurfaceStreaming(applyA2uiMessages(null, MESSAGES))).toBe(false)
  })

  it('is true while the outline skeleton is still pending', () => {
    const skeleton: Surface = {
      surfaceKind: 'presentation',
      root: 'deck',
      components: [
        { id: 'deck', component: 'SlideDeck', children: ['s1'] },
        { id: 's1', component: 'Slide', title: 'Why now', pending: true },
      ],
      dataModel: {},
    }
    expect(isSurfaceStreaming(skeleton)).toBe(true)
  })

  it('survives a cycle rather than hanging', () => {
    const looped: Surface = {
      surfaceKind: 'document',
      root: 'a',
      components: [
        { id: 'a', component: 'Column', children: ['b'] },
        { id: 'b', component: 'Column', children: ['a'] },
      ],
      dataModel: {},
    }
    expect(isSurfaceStreaming(looped)).toBe(false)
  })

  it('is false for no surface at all', () => {
    expect(isSurfaceStreaming(null)).toBe(false)
  })
})
