"""
UC Metrics to SQL Transpilation

Converts Unity Catalog Metrics Store definitions to standalone SQL queries.

This module provides transpilation from UC Metrics YAML format (generated by
yaml_to_uc_metrics.py) into standalone SQL SELECT statements that can be
executed independently for testing, analysis, or cross-platform compatibility.

Key features:
- Extracts Spark SQL expressions from UC Metrics measures
- Builds complete SELECT statements with table references
- Handles window functions and configurations
- Processes filter conditions into WHERE clauses
- Supports both single and consolidated UC Metrics formats
"""

import logging
from typing import Any, Dict, List, Optional, Union

import yaml

logger = logging.getLogger(__name__)


class UCMetricsToSqlTranspiler:
    """
    UC Metrics to SQL transpilation engine.

    Converts UC Metrics YAML definitions into standalone SQL SELECT statements
    that can be executed independently of Databricks Unity Catalog.

    Features:
    - Parse UC Metrics YAML format (single or consolidated)
    - Extract Spark SQL expressions from measures
    - Build complete SELECT statements with FROM clauses
    - Handle window function configurations
    - Process filter conditions into WHERE clauses
    - Generate executable SQL for testing and portability

    Usage:
        transpiler = UCMetricsToSqlTranspiler()

        # From YAML string
        sql_queries = transpiler.transpile_from_yaml(uc_metrics_yaml)

        # From dictionary
        sql_queries = transpiler.transpile(uc_metrics_dict)

    Example:
        Input UC Metrics YAML:
            version: "0.1"
            description: "Sales metrics"
            source: "main.sales.transactions"
            filter: "year = 2024"
            measures:
              - name: "total_revenue"
                expr: "SUM(amount)"

        Output SQL:
            -- total_revenue
            SELECT SUM(amount) as total_revenue
            FROM main.sales.transactions
            WHERE year = 2024;
    """

    def __init__(self):
        """Initialize UC Metrics to SQL transpiler."""
        self.logger = logging.getLogger(__name__)

    def transpile_from_yaml(
        self, uc_metrics_yaml: str, table_reference: Optional[str] = None
    ) -> List[str]:
        """
        Transpile UC Metrics YAML to standalone SQL queries.

        Args:
            uc_metrics_yaml: UC Metrics definition in YAML format
            table_reference: Optional table reference override (catalog.schema.table)

        Returns:
            List of SQL SELECT statements (one per measure)

        Raises:
            ValueError: If YAML is invalid or missing required fields
        """
        try:
            uc_metrics_dict = yaml.safe_load(uc_metrics_yaml)
            return self.transpile(uc_metrics_dict, table_reference)
        except yaml.YAMLError as ex:
            raise ValueError(f"Invalid YAML format: {ex}")

    def transpile(
        self, uc_metrics: Dict[str, Any], table_reference: Optional[str] = None
    ) -> List[str]:
        """
        Transpile UC Metrics dictionary to standalone SQL queries.

        Args:
            uc_metrics: UC Metrics definition as dictionary
            table_reference: Optional table reference override

        Returns:
            List of SQL SELECT statements (one per measure)

        Raises:
            ValueError: If UC Metrics format is invalid
        """
        # Validate UC Metrics format
        self._validate_uc_metrics(uc_metrics)

        # Extract components
        measures = uc_metrics.get("measures", [])
        source_table = table_reference or uc_metrics.get("source")
        common_filter = uc_metrics.get("filter")

        # Build SQL queries for each measure
        sql_queries = []
        for measure in measures:
            sql = self._build_sql_for_measure(
                measure=measure, source_table=source_table, common_filter=common_filter
            )
            sql_queries.append(sql)

        return sql_queries

    def _validate_uc_metrics(self, uc_metrics: Dict[str, Any]) -> None:
        """
        Validate UC Metrics format.

        Args:
            uc_metrics: UC Metrics dictionary

        Raises:
            ValueError: If format is invalid
        """
        if not isinstance(uc_metrics, dict):
            raise ValueError("UC Metrics must be a dictionary")

        if "measures" not in uc_metrics:
            raise ValueError("UC Metrics must contain 'measures' field")

        measures = uc_metrics["measures"]
        if not isinstance(measures, list):
            raise ValueError("'measures' must be a list")

        if len(measures) == 0:
            raise ValueError("'measures' list cannot be empty")

        # Validate each measure
        for idx, measure in enumerate(measures):
            if not isinstance(measure, dict):
                raise ValueError(f"Measure {idx} must be a dictionary")

            if "name" not in measure:
                raise ValueError(f"Measure {idx} missing required 'name' field")

            if "expr" not in measure:
                raise ValueError(f"Measure {idx} missing required 'expr' field")

    def _build_sql_for_measure(
        self,
        measure: Dict[str, Any],
        source_table: Optional[str],
        common_filter: Optional[str],
    ) -> str:
        """
        Build standalone SQL SELECT statement for a single measure.

        Args:
            measure: Measure definition with name, expr, and optional window
            source_table: Source table reference (catalog.schema.table)
            common_filter: Common filter conditions

        Returns:
            Complete SQL SELECT statement
        """
        measure_name = measure["name"]
        measure_expr = measure["expr"]
        window_config = measure.get("window")

        # Build SELECT clause
        if window_config:
            # Handle window functions
            select_expr = self._build_window_expression(measure_expr, window_config)
        else:
            # Regular expression
            select_expr = measure_expr

        # Build SQL components
        sql_parts = []

        # Comment with measure name
        sql_parts.append(f"-- {measure_name}")

        # SELECT clause
        sql_parts.append(f"SELECT {select_expr} as {measure_name}")

        # FROM clause (if source table is provided)
        if source_table:
            sql_parts.append(f"FROM {source_table}")

        # WHERE clause (if filter is provided)
        if common_filter:
            sql_parts.append(f"WHERE {common_filter}")

        # Combine and return
        sql = "\n".join(sql_parts) + ";"

        return sql

    def _build_window_expression(
        self, base_expr: str, window_config: Union[List[Dict[str, str]], Dict[str, str]]
    ) -> str:
        """
        Build SQL window function expression from window configuration.

        UC Metrics window config example:
            [
                {
                    "order": "date",
                    "range": "current",
                    "semiadditive": "last"
                }
            ]

        Args:
            base_expr: Base measure expression
            window_config: Window configuration (list or dict)

        Returns:
            SQL window expression
        """
        # Normalize window config to list
        if isinstance(window_config, dict):
            window_configs = [window_config]
        else:
            window_configs = window_config

        # For now, handle simple semiadditive patterns
        # This can be extended based on actual UC Metrics window semantics

        # Check if this is a semiadditive aggregation
        for config in window_configs:
            semiadditive = config.get("semiadditive")
            order_field = config.get("order")

            if semiadditive == "last" and order_field:
                # Convert to SQL window function with LAST_VALUE or similar
                # Example: LAST_VALUE(expr) OVER (PARTITION BY ... ORDER BY date)
                window_expr = (
                    f"LAST_VALUE({base_expr}) OVER ("
                    f"ORDER BY {order_field} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)"
                )
                return window_expr

        # Default: return base expression with window note
        self.logger.warning(
            f"Window configuration not fully transpiled: {window_config}. "
            f"Using base expression."
        )
        return f"{base_expr} /* window: {window_config} */"
